name: fawri_app_refactor
description: A new Flutter project.

publish_to: "none"

version: 2.0.4+58
environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_bottom_navigation_bar: ^1.4.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  awesome_dialog: ^3.2.1
  url_launcher: ^6.0.20
  sentry_flutter: ^9.5.0
  awesome_notifications: ^0.10.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_localization: ^0.3.0
  google_sign_in_android: ^6.1.34
  sqflite: ^2.4.2
  dartz: ^0.10.1
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  flame: ^1.25.0
  flutter_native_splash: ^2.4.0
  flutter_html: ^3.0.0-alpha.3
  shared_preferences: ^2.0.8
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.0.0
  flutter_slidable: ^4.0.0
  list_wheel_scroll_view_nls: ^0.0.3
  flutter_libphonenumber: ^2.5.1
  scrollable_positioned_list: ^0.3.5
  audioplayers: ^6.2.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.5.0
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  flutter_swiper_view: ^1.1.8
  path_provider: ^2.1.5
  path: ^1.9.0
  http: ^1.2.2
  json_path: ^0.7.4
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.1.18
  flutter_fortune_wheel: ^1.3.2
  flutter_vector_icons: ^2.0.0
  vibration: ^3.1.3
  flutter_animate: ^4.2.0+1
  showcaseview: ^4.0.1
  uuid: ^4.5.1
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^8.1.2
  like_button: ^2.0.5
  dots_indicator: ^4.0.1
  shimmer: ^3.0.0
  firebase_dynamic_links:
  connectivity_plus: ^6.1.4
  flutter_switch: ^0.3.2
  provider: ^6.0.5
  flutter_image_slideshow: ^0.1.6
  add_to_cart_animation: ^2.0.4
  bouncerwidget: ^0.0.5
  photo_view: ^0.15.0
  share_plus: ^10.1.3
  firebase_remote_config: ^5.1.3
  flutter_arc_text: ^0.6.0
  crypto: ^3.0.1
  lottie: ^3.2.0
  easy_date_timeline: ^2.0.9
  marquee: ^2.2.3
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues
  glowy_borders: ^1.0.2
  rxdart: ^0.28.0
  flutter_svg: ^2.0.17
  badges: ^3.1.2
  salomon_bottom_bar: ^3.3.2
  firebase_in_app_messaging: ^0.8.1
  app_links: ^6.3.3
  flutter_typeahead: ^5.2.0
  flashy_tab_bar2: ^0.0.10
  csv: ^6.0.0
  dropdown_search: ^6.0.1
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  in_app_review: ^2.0.10
  flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_crashlytics: ^4.1.3
  fading_edge_scrollview:
  firebase_core: ^3.6.0
  firebase_analytics: ^11.5.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^5.3.1
  firebase_core_platform_interface: ^6.0.0
  cloud_firestore: ^5.4.3
  hive_flutter:
  loading_animation_widget:
  cuberto_bottom_bar: ^3.1.0
  flexible_dropdown: ^1.0.6
  dropdown_button2: ^2.3.9
  animations:
  dio: ^5.7.0
  neon_circular_timer: ^0.0.7
  simple_circular_progress_bar: ^1.0.2
  flutter_lints: ^5.0.0
  rate_my_app: ^2.3.1
  animated_custom_dropdown: ^3.1.1
  chips_choice: ^3.0.1
  rating_and_feedback_collector: ^0.0.3
  popover: ^0.3.1
  flame_bloc: ^1.12.7
  flutter_bloc: ^8.1.6
  vimeo_video_player: ^1.0.1
  video_player: ^2.9.5
  equatable: ^2.0.7
  flutter_soloud: ^3.0.2
  facebook_app_events: ^0.20.1
  #  device_preview: ^1.2.0
  get_it: ^8.0.3
dependency_overrides:
  collection: 1.19.0
  sqflite_android: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0

flutter_native_splash:
  android: true
  ios: true
  color: "#FfFfFf"  # Replace with your desired color
  image: "assets/images/image.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_icons:
  android: "launcher_icon"  # Generate icons for Android
  ios: true                 # Generate icons for iOS
  image_path: "assets/icon/appstore.png"  # Correct path to your image
  min_sdk_android: 23       # Set the minimum SDK version for Android

flutter:
  uses-material-design: true
  generate: true
  #  synthetic-package: false
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico/Pacifico-Regular.ttf
    - family: Chewy
      fonts:
        - asset: fonts/Chewy/Chewy-Regular.ttf

    - family: Rubik
      fonts:
        - asset: fonts/Rubik/static/Rubik-Medium.ttf
        - asset: fonts/Rubik/Rubik-VariableFont_wght.ttf
          weight: 400
    - family: CrimsonText
      fonts:
        - asset: fonts/Crimson/CrimsonText-Bold.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600

    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/images/rating/
    - assets/images/departments/
    - assets/icons/
    - assets/images/game_images/
    - assets/audios/
    - assets/pdfs/
    - assets/lottie/

