services:
  - type: web
    name: firstprojectflutterweb
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: FLUTTER_VERSION
        value: 3.38.0


