name: flutter_web_shelf_server
description: A simple Shelf server to serve Flutter web build assets
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0


